[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nginx"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction --no-scripts"]

[phases.build]
cmds = [
  "composer dump-env prod",
  "php bin/console cache:clear --env=prod --no-debug",
  "php bin/console assets:install public --env=prod"
]

[start]
cmd = "sh bin/start.sh"
